---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "api-config"
  namespace: "api"
  labels:
    app: "api"
data:
  POSTGRES_URL: "postgres endpoint url"
  METRICS_URL: "metric endpoint url"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "api"
  namespace: "api"
  labels:
    app: "api"
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: "api"
  template:
    metadata:
      labels:
        app: "api"
    spec:
      containers:
        - name: "api-container"
          image: "accountid.dkr.ecr.ap-southeast-1.amazonaws.com/api:prod"
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /api
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 20
            failureThreshold: 5
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /api
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 20
            failureThreshold: 5
            timeoutSeconds: 5
          resources:
            requests:
              memory: "2G"
              cpu: "1"
            limits:
              memory: "2G"
              cpu: "1"
          env:
            - name: TZ
              value: Asia/Ho_Chi_Minh
            - name: "DB_USER"
              valueFrom:
                secretKeyRef:
                  name: "postgres"
                  key: user
            - name: "DB_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: "postgres"
                  key: password
          envFrom:
            - configMapRef:
                name: api-config
---
apiVersion: "autoscaling/v2"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "api-hpa"
  namespace: "api"
  labels:
    app: "api"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "api"
    apiVersion: "apps/v1"
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: "Resource"
      resource:
        name: "memory"
        target:
          type: Utilization
          averageUtilization: 85
    - type: "Resource"
      resource:
        name: "cpu"
        target:
          type: Utilization
          averageUtilization: 85
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "api"
  namespace: "api"
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /api
  labels:
    app: "api"
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: "TCP"
  type: "NodePort"
  selector:
    app: "api"
